version: "3.9"
services:
  app:
    build: ./infra/php
    volumes:
      - ./src:/app

  web:
    image: nginx:1.20-alpine
    ports:
      - 8080:80
    volumes:
      - ./src:/app
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /app

  db:
    build: ./infra/mysql
    volumes:
      - db-store:/var/lib/mysql

volumes:
  db-store:
