version: "3.9"
services:
  app:
    build: ./infra/php
    container_name: collect_app
    volumes:
      - ./src:/app

  web:
    image: nginx:1.20-alpine
    container_name: collect_web
    ports:
      - 8080:80
    volumes:
      - ./src:/app
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /app

  db:
    build: ./infra/mysql
    container_name: collect_db
    volumes:
      - db-store:/var/lib/mysql

  db-testing:
    build: ./infra/mysql
    container_name: test_collect_db
  
  storybook:
    image: node:12.22.12-alpine
    container_name: collect_storybook
    tty: true
    volumes: 
      - ./src:/app
    working_dir: /app
    ports:
      - 9001:9001

volumes:
  db-store:
